"""init migration

Revision ID: 4f52a8b7eac0
Revises: None
Create Date: 2014-11-20 19:37:38.631796

"""

# revision identifiers, used by Alembic.
revision = '4f52a8b7eac0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
